language: java

jdk:
  - openjdk8

services:
  - docker

addons:
  sonarcloud:
    organization: "nlco"
#    token:
#      secure: "**************************" # encrypted value of your token

before_script:
  - cd ./docker/dev/
  - docker-compose up -d
  - cd ../../src

script:
  #- mvn clean validate
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=NlCO_OCP9 -Dsonar.login=2d88d4f0e2eeef807af3262bac7d4e0cfb8d37f3

after_script:
  - cd ../docker/dev
  - docker-compose stop
  - docker-compose rm -f
